config/routes.rb
Rails.application.routes.draw do
  root 'landing#page'

  resources :posts
  resources :subjects
  get 'admin/home'

  devise_for :admins
  get 'home/page'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :subject
  belongs_to :user
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, format:{with: /@student.com/}
  has_many :posts
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def home

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:year])
   devise_parameter_sanitizer.permit(:account_update) do |user|
     user.permit(:username,:year, :password, :password_confirmation, :current_password)
   end
 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def page
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_subject, only: [:create, :new,:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    # @posts = @subject.posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new

    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id if current_user
    # @post.subject_id = @subject.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_subject
      @subject = Subject.find(params[:subject_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :approved, :subject_id, :user_id,)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.where(year:params[:year])
    # @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subject_name, :year)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/admin/home.html.erb
<h1>Admin#home</h1>
<p>Find me in app/views/admin/home.html.erb</p>

app/views/home/page.html.erb
<h1> Choose the year</h1>
<div class = "block-align">
<div class= "row">
  <div class = "col-md-3">
    <%=link_to "year 1",subjects_path(year:1),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 2",subjects_path(year:2),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 3",subjects_path(year:3),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 4",subjects_path(year:4),class: "btn btn-info"%>
  </div>
</div>
<br>
<br>
<br>
<div class= "row">
  <div class = "col-md-3">
    <%=link_to "year 5",subjects_path(year:5),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 6",subjects_path(year:6),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 7",subjects_path(year:7),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 8",subjects_path(year:8),class: "btn btn-info"%>
  </div>
</div>
<br>
<br>
<br>
<div class= row>
  <div class = "col-md-3">
    <%=link_to "year 9",subjects_path(year:9),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 10",subjects_path(year:10),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 11",subjects_path(year:11),class: "btn btn-info"%>
  </div>
  <div class = "col-md-3">
    <%=link_to "year 12",subjects_path(year:12),class: "btn btn-info"%>
  </div>
</div>
</div>

app/views/landing/page.html.erb
<h1>Landing#page</h1>
<p>style this page: This is the view for unsigned user</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'partials/nav'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Submit</button>
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'year',home_page_path%>
          </li>
          <li>
            <%= link_to 'Add subjects',new_subject_path%>
          </li>
          <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </li>
          <li>
              <%= link_to('Edit registration', edit_user_registration_path) %>
          </li>
          <% else %>
          <li>
            <%= link_to('Login', new_user_session_path)  %>
          </li>
          <li>
            <%= link_to('Register', new_user_registration_path)  %>
          </li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, url: posts_path(subject_id: @subject.id)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <!-- <!-%= f.input :subject_id, input_html: { value: params[:subject_id]}, as: :hidden %> -->

     <!-- approoval must be allowed only for admin -->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Approved</th>
      <th>Subject</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.approved %></td>
        <td><%= post.subject%></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @post.approved %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @post.subject %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/subjects/_form.html.erb
<%= simple_form_for(@subject) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject_name %>
    <%= f.input :year %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <!-- <thead>
    <tr>
      <th>Subject name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->
    <tbody>
    <% Subject.all.each do |subject| %>
      <tr>
        <td><%= subject.subject_name %></td>
        <td><%= link_to 'Show', posts_path %></td>
        <td><%= link_to "Add post",new_post_path(subject_id: subject.id),class: "btn btn-info"%></td>

      </tr>
   <% end %>
   </tbody>


</table>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject name:</strong>
  <%= @subject.subject_name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @subject.year %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> 
<%= link_to 'Back', subjects_path %>